cmd_/home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/fastpath-0.1/filter.o := rsdk-linux-gcc -Wp,-MD,/home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/fastpath-0.1/.filter.o.d  -nostdinc -isystem /home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/staging_dir/rsdk-4.6.4-4181-EB-3.10-0.9.33-m32u-20141001/bin/../lib/gcc/mips-linux-uclibc/4.6.4/include -I/home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/linux-3.10.49/arch/rlx/include -Iarch/rlx/include/generated  -Iinclude -I/home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/linux-3.10.49/arch/rlx/include/uapi -Iarch/rlx/include/generated/uapi -I/home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/linux-3.10.49/include/uapi -Iinclude/generated/uapi -include /home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/linux-3.10.49/include/linux/kconfig.h -D__KERNEL__ -DVMLINUX_LOAD_ADDRESS=0x80000000 -DDATAOFFSET=0  -D__ASSEMBLY__  -mno-check-zero-division -mabi=32 -G 0 -mno-abicalls -fno-pic -pipe -ffreestanding -EB -UMIPSEB -U_MIPSEB -U__MIPSEB -U__MIPSEB__ -UMIPSEL -U_MIPSEL -U__MIPSEL -U__MIPSEL__ -DMIPSEB -D_MIPSEB -D__MIPSEB -D__MIPSEB__ -I/home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/linux-3.10.49/arch/rlx/ -I/home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/linux-3.10.49/arch/rlx/soc-rtl8196e/ -Iinclude/asm-rlx -I/home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/linux-3.10.49/arch/rlx/include/asm/mach-generic        -I /home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/linux-3.10.49/net -D__KERNEL__ -DCONFIG_RTK_IPTABLES_FAST_PATH -DCONFIG_FAST_PATH_MODULE  -DMODULE -mlong-calls  -c -o /home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/fastpath-0.1/filter.o /home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/fastpath-0.1/filter.S

source_/home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/fastpath-0.1/filter.o := /home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/fastpath-0.1/filter.S

deps_/home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/fastpath-0.1/filter.o := \

/home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/fastpath-0.1/filter.o: $(deps_/home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/fastpath-0.1/filter.o)

$(deps_/home/slobodan/OLDopenwrt-rtk/rtk_openwrt_src/build_dir/target-mips-rlx4181-linux/linux-realtek_rtl8196e/fastpath-0.1/filter.o):
